name: neartalk
description: Simple chat app using nearby connections API

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_gen_runner: ^5.5.0+1
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.3.7
  flutter_screenutil: ^5.9.1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hooked_bloc: ^1.4.3
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.8
  injecteo: ^1.0.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  location: ^5.0.3
  logger: ^2.0.2+1
  nearby_connections: ^4.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  photo_view: ^0.15.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  injecteo_generator: ^1.0.1
  linteo: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
